### ISSUE TITLE
Service calls miss entity_id (or area_id)

### ISSUE THREAD

**Issue by kaosmagix** [DBuit/switch-popup-card#4]
I try to use the popup card as a popup for a template sensor button (the sensor has a state depending on the status of a few input_boolean's). In the popup I try to set a specific input_boolean on/off. But I cannot get that to work the issue is always an error that the service input_boolean.turn_on is missing the entity_id. The popup opens with the correct state selected (so reading the correct state of the sensor works, but the service call doesn't.

This is my code:
```
  rows:
  - row: 1
    columns:
    - column: 1
      tileOnRow: 3
      entities:
      - title: Algemeen
        entities:
        - entity: sensor.mode_home
          popup:
            type: custom:switch-popup-card
            noActiveState: '-'
            entity_value_path: state
            entities:
            - sensor.mode_home
            buttons:
            - icon: "mdi:white-balance-sunny"
              value: "day"
              name: "Day"
              color: "#FFF"
              icon_color: "rgba(255,255,255,1)"
            - icon: "mdi:home-export-outline"
              value: "away"
              name: "Away"
              color: "#FFF"
              icon_color: "rgba(255,255,255,1)"
            - icon: "mdi:account-question"
              value: "guest"
              name: "Guest"
              color: "#FFF"
              icon_color: "rgba(255,255,255,1)"
            - icon: "mdi:weather-night"
              value: "sleep"
              name: "Sleep"
              color: "#FFF"
              icon_color: "rgba(255,255,255,1)"
              service: input_boolean.turn_on
              service_data:
              entity_id: input_boolean.mode_sleep
            - icon: "mdi:power-sleep"
              value: "goodnight"
              name: "Goodnight"
              color: "#FFF"
              icon_color: "rgba(255,255,255,1)"
              service: input_boolean.turn_on
              service_data:
              entity_id: input_boolean.mode_goodnight
``` 

Do I something wrong or is this just not possible? Any help appreciated.
